name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.469'
        lein: 2.9.4

    - name: Clojure dependency cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('project.clj') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Verify Tests
      run: lein test

    - name: Verify Lint
      run: clojure -Sdeps '{:deps {clj-kondo {:mvn/version "RELEASE"}}}' -m clj-kondo.main --lint src --config .clj-kondo/config.edn

    - name: Release snapshot to Clojars
      if: github.ref == 'refs/heads/main'
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: |
        lein deploy clojars-ci
